name: opus_codec_dart
version: 3.0.5
description: >
  Wraps libopus in dart, and additionally provides a dart friendly API for
  encoding and decoding.
repository: https://github.com/Corkscrews/opus_flutter/tree/master/opus_dart

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  wasm_ffi: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^5.0.0
  mockito: ^5.4.0
  test: ^1.24.0
