name: opus_flutter_web
description: Web implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_web
version: 3.0.3

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  opus_flutter_platform_interface:
    path: ../opus_flutter_platform_interface
  wasm_ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/libopus.js
    - assets/libopus.wasm
  plugin:
    implements: opus_flutter
    platforms:
      web:
        pluginClass: OpusFlutterWeb
        fileName: opus_flutter_web.dart
