name: opus_flutter_android
description: Android implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_android
version: 3.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.epnw.opus_flutter_android
        pluginClass: OpusFlutterAndroidPlugin