name: opus_flutter_linux
description: Linux implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_linux
version: 3.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface: ^3.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/libopus_x86_64.so.blob
    - assets/libopus_aarch64.so.blob
  plugin:
    implements: opus_flutter
    platforms:
      linux:
        dartPluginClass: OpusFlutterLinux
        pluginClass: none
