name: opus_codec_linux
description: Linux implementation of the opus_codec plugin.
repository: https://github.com/ppamorim/opus_codec/tree/master/opus_flutter_linux
version: 3.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_codec_platform_interface:
    path: ../opus_flutter_platform_interface
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/libopus_x86_64.so.blob
    - assets/libopus_aarch64.so.blob
  plugin:
    implements: opus_codec
    platforms:
      linux:
        dartPluginClass: OpusFlutterLinux
