name: opus_codec_example
description: Demonstrates how to use the opus_codec plugin.
version: 2.0.0+2
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  opus_codec_dart:
    path: ../../opus_dart
  flutter:
    sdk: flutter
  share_plus: ^10.0.0
  opus_codec:
    path: ../
  cupertino_icons: ^1.0.8
  platform_info: ^5.0.0
  record: ^6.2.0
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  google_fonts: ^8.0.2
  flutter_bloc: ^9.0.0
  universal_io: ^2.3.1
dependency_overrides:
  opus_codec_android:
    path: ../../opus_flutter_android
  opus_codec_ios:
    path: ../../opus_flutter_ios
  opus_codec_linux:
    path: ../../opus_flutter_linux
  opus_codec_macos:
    path: ../../opus_flutter_macos
  opus_codec_platform_interface:
    path: ../../opus_flutter_platform_interface
  opus_codec_web:
    path: ../../opus_flutter_web
  opus_codec_windows:
    path: ../../opus_flutter_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw
    - assets/download.js
