name: opus_flutter_windows
description: Windows implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_windows
version: 3.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface:
    path: ../opus_flutter_platform_interface
  path_provider: ^2.1.5
  universal_io: ^2.2.2

dependency_overrides:
  # platform 3.0.0 references Platform.packageRoot which was removed from the
  # Dart SDK. Force a version that does not use that deprecated API.
  platform: ">=3.1.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/opus_license.txt
    - assets/libopus_x64.dll.blob
    - assets/libopus_x86.dll.blob
  plugin:
    implements: opus_flutter
    platforms:
      windows:
        dartPluginClass: OpusFlutterWindows
        pluginClass: none
