name: opus_flutter
description: Loads a DynamicLibrary of opus for usage with opus_dart on flutter platforms.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter
version: 3.0.3
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface:
    path: ../opus_flutter_platform_interface
  opus_flutter_android:
    path: ../opus_flutter_android
  opus_flutter_ios:
    path: ../opus_flutter_ios
  opus_flutter_linux:
    path: ../opus_flutter_linux
  opus_flutter_macos:
    path: ../opus_flutter_macos
  opus_flutter_windows:
    path: ../opus_flutter_windows
  opus_flutter_web:
    path: ../opus_flutter_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: opus_flutter_android
      ios:
        default_package: opus_flutter_ios
      linux:
        default_package: opus_flutter_linux
      macos:
        default_package: opus_flutter_macos
      windows:
        default_package: opus_flutter_windows
      web:
        default_package: opus_flutter_web