name: opus_flutter
description: Loads a DynamicLibrary of opus for usage with opus_dart on flutter platforms.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter
version: 3.0.3

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface: ^3.0.0
  opus_flutter_android: ^3.0.1
  opus_flutter_ios: ^3.0.1
  opus_flutter_linux: ^3.0.0
  opus_flutter_macos: ^3.0.0
  opus_flutter_windows: ^3.0.0
  opus_flutter_web: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: opus_flutter_android
      ios:
        default_package: opus_flutter_ios
      linux:
        default_package: opus_flutter_linux
      macos:
        default_package: opus_flutter_macos
      windows:
        default_package: opus_flutter_windows
      web:
        default_package: opus_flutter_web