name: opus_codec
description: Loads a DynamicLibrary of opus for usage with opus_codec_dart on flutter platforms.
repository: https://github.com/Corkscrews/opus_flutter/tree/master/opus_flutter
version: 3.0.4

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  opus_codec_platform_interface: ^3.0.0
  opus_codec_android: ^3.0.1
  opus_codec_ios: ^3.0.1
  opus_codec_linux: ^3.0.0
  opus_codec_macos: ^3.0.0
  opus_codec_windows: ^3.0.0
  opus_codec_web: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: opus_codec_android
      ios:
        default_package: opus_codec_ios
      linux:
        default_package: opus_codec_linux
      macos:
        default_package: opus_codec_macos
      windows:
        default_package: opus_codec_windows
      web:
        default_package: opus_codec_web
